name: geo
channels:
  - conda-forge
dependencies:
  - gdal=3.4.3
  - pip
  - pip:
      - geopandas
      - keplergl
      - streamlit
      - localtileserver
      - palettable
      - streamlit-folium
      - streamlit-keplergl
      - streamlit-bokeh-events

